const express = require('express')
const router = express.Router()

const userRoute = require('./user.routes.js')
const commonRoute = require('./commom.routes.js')
const adminRoute = require('./admin.routes.js')
const reportTypeRoute = require('./reportType.routes.js')
const categoryStreamRoute = require('./categoryStream.routes.js')
const streamerRoute = require('./streammer.routes.js')
const streamRoute = require('./stream.routes.js')
const postRoute = require('./post.routes')
const categoryPostRoute = require('./categoryPost.routes')
const commentRoute = require('./commentPost.routes')
const reportPostCategoryRoute = require('./reportPostCategory.routes')
const reportPostRoute = require('./reportPost.routes')

router.use('/api/v1/user', userRoute)
router.use('/api/v1/commom', commonRoute)
router.use('/api/v1/admin', adminRoute)
router.use('/api/v1/report-type', reportTypeRoute)
router.use('/api/v1/category-stream', categoryStreamRoute)
router.use('/api/v1/streammer', streamerRoute)
router.use('/api/v1/stream', streamRoute)
router.use('/api/v1/post', postRoute)
router.use('/api/v1/category-post', categoryPostRoute)
router.use('/api/v1/comments', commentRoute)
router.use('/api/v1/report-post-category', reportPostCategoryRoute)
router.use('/api/v1/report-post', reportPostRoute)

module.exports = router
